# src/config/settings.yaml

spark:
  app_name: "Payments Report"

sources:
  orders:
    path: "./fiap-dep-payments-pipeline/datasets/datasets-csv-pedidos/data/pedidos/"
    format: "csv"
    options:
      header: true
      sep: ";"
      compression: "gzip"

  payments:
    path: "./fiap-dep-payments-pipeline/datasets/datasets-json-pagamentos/data/pagamentos/"
    format: "json"
    options: {}

sink:
  sales_report:
    path: "./fiap-dep-payments-pipeline/datasets/output/sales_report_2025"
    format: "parquet"
    mode: "overwrite"